/**
 * The FFT band filter matches legacy, byte for byte.
 *
 * `test/fixtures/legacy-fft.json` holds the exact outputs numpy produces, generated by
 * `generate_fft_goldens.py` beside it. Two of the six cases are odd-sized, which is what
 * distinguishes legacy's `fftshift`-instead-of-`ifftshift` from the correct inverse: a port that
 * "fixes" it passes the four even cases and fails those two.
 */

import { readFile } from "node:fs/promises";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

import { beforeAll, describe, expect, it } from "vitest";

import { filterFrequencies } from "../../src/tools/fft.js";

const FIXTURE = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
  "fixtures",
  "legacy-fft.json",
);

interface Case {
  readonly label: string;
  readonly height: number;
  readonly width: number;
  readonly frequencyThresholds: readonly number[];
  readonly intensityThresholds: readonly number[];
  readonly input: readonly number[];
  readonly expected: readonly number[];
}

let cases: readonly Case[];

beforeAll(async () => {
  cases = (JSON.parse(await readFile(FIXTURE, "utf8")) as { cases: Case[] }).cases;
});

describe("against legacy's own output", () => {
  it("has both even and odd cases, or it proves less than it claims", () => {
    expect(cases.some((c) => c.height % 2 === 0)).toBe(true);
    expect(cases.some((c) => c.height % 2 === 1)).toBe(true);
  });

  it("matches on every case", () => {
    const failures: string[] = [];

    for (const testCase of cases) {
      const result = filterFrequencies(
        Uint8Array.from(testCase.input),
        testCase.height,
        testCase.width,
        testCase.frequencyThresholds,
        testCase.intensityThresholds,
      );

      // Decision 10's tolerance is for GPU nondeterminism; this is deterministic arithmetic, so
      // the bar is exact. A single byte of drift means a rounding step is in the wrong place.
      const wrong = [...result].reduce(
        (count, value, index) => count + (value === testCase.expected[index] ? 0 : 1),
        0,
      );

      if (wrong > 0) {
        failures.push(`${testCase.label}: ${wrong} of ${result.length} bytes differ`);
      }
    }

    expect(failures).toEqual([]);
  });
});
