"""Version information for PyInstaller bundle.

This file is auto-generated by the build script from pyproject.toml.
Do not edit manually - changes will be overwritten during build.
"""

__version__ = "1.4.1"
